function [mol,H,X,info] = scf(mol,options)
% SCF Self Consistent Field iteration.
%    [mol,H,X,info] = SCF(mol,options) adopts Self Consistent Field (SCF)
%    iteration to find the ground state minimum total energy and the
%    corresponding wave functions. mol is a Molecule object and options is
%    the options for running the SCF. Please read setksopt for detailed
%    information about options. SCF returns the molecule mol with/without
%    force, the Hamiltonian H, the wave functions X, and the information
%    for each iteration in info. If a crystal object is input instead of
%    molecule, the results will be generated by scf4c. If a molecule object
%    with non-zero temperature is input, the results will be generated by
%    scf4m.
%
%   See also scf4m, scf4c, dcm, trdcm.

%  Copyright (c) 2016-2017 Yingzhou Li and Chao Yang,
%                          Stanford University and Lawrence Berkeley
%                          National Laboratory
%  This file is distributed under the terms of the MIT License.

if (nargin < 2)
    % by default we it uses 'lobpcg' as a eigensolver method
    options = setksopt();
end

if isa(mol,'Crystal')
    [mol,H,X,info] = scf4c(mol,options);
    return;
elseif mol.temperature > 0
    [mol,H,X,info] = scf4m(mol,options);
    return;
end

% Set timer
tstart  = cputime;

% Initialize input variables
verbose    = ~strcmpi(options.verbose,'off');
force      = options.force;
maxscfiter = options.maxscfiter;
scftol     = options.scftol;
what2mix   = options.what2mix;
mixtype    = options.mixtype;
mixdim     = options.mixdim;
betamix    = options.betamix;
brank      = options.brank;
X          = options.X0;
rho        = options.rho0;

nspin      = mol.nspin;

% Initialize Hamiltonian, Wavefun, and Preconditioners
[mol,H,X,Hprec,nocc] = iterinit(mol,rho,X);
ev = [];

% calculate Ewald and Ealphat
Eewald     = getEewald(mol);
Ealphat    = getEalphat(mol);

vion       = H.vion;
vext       = H.vext;
vtot       = H.vtot;
rho        = H.rho;

% Initialize output variables
Etotvec    = zeros(maxscfiter,1);
scferr     = zeros(maxscfiter,1);
dfmat      = [];
dvmat      = [];
cdfmat     = [];

fprintf('Beging SCF calculation for %s...\n',mol.name);
vtoterr = 1e-1;
tic;

for iterscf = 1:maxscfiter
    
    fprintf('SCF iter %3d:\n', iterscf);
    
    rhoin  = rho;
    vtotin = vtot;
    
    % compute X^{i+1} given by 
    %  H^{i}  X^{i+1} =  X^{i+1} Lambda^{i+1} 
    %options.cgtol = vtoterr/10;
    [X, ev] = updateX(mol, H, X, Hprec, options);
    
    % Update density function rho
    % rho^{i+1} = diag(X^{i+1}^* X^{i+1})
    rho = getcharge(mol,X);
    % update H, using the rho coming from the computation of the new 
    % eigen functions 
    H.rho = rho;
    
    % potential mixing section 4.4.1 
    if strcmpi(what2mix,'rho')
        rhoerr = norm(rho(:)-rhoin(:))/norm(rhoin(:));
        scferr(iterscf) = rhoerr;
        fprintf('Rel Rho Err     = %20.3e\n',rhoerr);
        [rho,dfmat,dvmat,cdfmat] = potmixing(mol,rhoin,rho,...
            iterscf,mixtype, betamix, ...
            dfmat, dvmat, cdfmat, mixdim, ...
            brank);
    end
    
    % Kinetic energy and some additional energy terms
    Ekin = (2/nspin)*sum(ev(1:nocc));
    % ionic and external potential energy was included in Ekin
    % along with incorrect Ecoul and Exc. Need to correct them
    % later;
    Ecor = getEcor(mol, rho, vtot, vion, vext);
    
    % Compute Hartree and exchange correlation energy and potential
    % using the new charge density; update the total potential
    [vhart,vxc,uxc2,rho]=getVhxc(mol,rho);
    
    % Update total potential
    vtot = getVtot(mol, vion, vext, vhart, vxc);
    if strcmpi(what2mix,'pot')
        vtoterr = norm(vtot(:)-vtotin(:))/norm(vtotin(:));
        scferr(iterscf) = vtoterr;
        fprintf('Rel Vtot Err    = %20.3e\n',vtoterr);
        [vtot,dfmat,dvmat,cdfmat] = ...
            potmixing(mol,vtotin,vtot,iterscf,mixtype,...
            betamix,dfmat,dvmat,cdfmat,mixdim,brank);
    end
    H.vtot = vtot;
    
    % Calculate the potential energy based on the new potential
    Ecoul = getEcoul(mol,abs(rho),vhart);
    Exc   = getExc(mol,abs(rho),uxc2);
    Etot = Eewald + Ealphat + Ekin + Ecor + Ecoul + Exc;
    Etotvec(iterscf) = Etot;
    
    % Convergence check
    fprintf('Total Energy    = %20.13e\n', Etot);
    [cvg,resfro] = reportconverge(H,X,iterscf,maxscfiter, ...
        scferr(iterscf),scftol,verbose);
    if cvg && iterscf > 3
        info.converge = true;
        break;
    end
    
end

X.occ = zeros(1,ncols(X));
X.occ(1:nocc) = 1;

toc;

if force
    mol.xyzforce = getFtot(mol,H,X,rho);
end

info.Eigvals = ev;
info.Etotvec = Etotvec(1:iterscf);
info.SCFerrvec = scferr(1:iterscf);

timetot = cputime - tstart;
fprintf('Etot            = %20.13e\n', Etot);
fprintf('Eone-electron   = %20.13e\n', Ekin+Ecor);
fprintf('Ehartree        = %20.13e\n', Ecoul);
fprintf('Exc             = %20.13e\n', Exc);
fprintf('Eewald          = %20.13e\n', Eewald);
fprintf('Ealphat         = %20.13e\n', Ealphat);
fprintf('--------------------------------------\n');
fprintf('Total time used = %20.3e\n', timetot);
fprintf('||HX-XD||_F     = %20.3e\n', resfro);

end
